# Generated by Django 5.0.6 on 2024-12-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0008_department_last_activity_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="facility",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="quarters",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="quarterstype",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
