# Generated by Django 5.0.6 on 2024-12-07 19:23

import address.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        ("facility", "0009_alter_department_slug_alter_facility_slug_and_more"),
        ("organization", "0005_alter_organization_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facultyprofile",
            options={
                "verbose_name": "Faculty Profile",
                "verbose_name_plural": "Faculty Profiles",
            },
        ),
        migrations.AlterField(
            model_name="facultyprofile",
            name="address",
            field=address.models.AddressField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_profiles",
                to="address.address",
            ),
        ),
        migrations.AlterField(
            model_name="facultyprofile",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_profiles",
                to="organization.organization",
            ),
        ),
        migrations.AlterField(
            model_name="facultyprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
