# Generated by Django 5.0.6 on 2024-12-12 23:53

import address.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        ("facility", "0010_alter_facultyprofile_options_and_more"),
        ("organization", "0005_alter_organization_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facultyprofile",
            name="address",
            field=address.models.AddressField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_profile",
                to="address.address",
            ),
        ),
        migrations.AlterField(
            model_name="facultyprofile",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_profile",
                to="organization.organization",
            ),
        ),
    ]
