# Generated by Django 5.2.8 on 2025-11-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0012_facultyprofile_slug"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Faculty",
        ),
    ]
