# Generated by Django 5.2.8 on 2025-11-19 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        ("facility", "0013_delete_faculty"),
        ("organization", "0007_organization_unique_org_slug_per_parent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facility",
            options={},
        ),
        migrations.AlterModelOptions(
            name="facultyprofile",
            options={},
        ),
        migrations.AddConstraint(
            model_name="facility",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="unique_facility_slug_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="facultyprofile",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="unique_faculty_slug_per_org"
            ),
        ),
    ]
