# Generated by Django 5.2.8 on 2025-11-19 11:39

import address.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        (
            "facility",
            "0014_alter_facility_options_alter_facultyprofile_options_and_more",
        ),
        ("organization", "0008_organization_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facultyprofile",
            options={
                "verbose_name": "Faculty Profile",
                "verbose_name_plural": "Faculty Profiles",
            },
        ),
        migrations.AlterField(
            model_name="facility",
            name="address",
            field=address.models.AddressField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_address",
                to="address.address",
            ),
        ),
        migrations.AddConstraint(
            model_name="facultyprofile",
            constraint=models.UniqueConstraint(
                fields=("facility", "user"), name="unique_faculty_per_facility_user"
            ),
        ),
    ]
