# Generated by Django 5.2.8 on 2025-11-23 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "facility",
            "0015_alter_facultyprofile_options_alter_facility_address_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="facultyprofile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="faculty",
                to="facility.department",
            ),
        ),
        migrations.AddField(
            model_name="facultyprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Facility Admin"),
                    ("DEPARTMENT_ADMIN", "Department Admin"),
                    ("STAFF", "Faculty"),
                ],
                default="STAFF",
                max_length=32,
            ),
        ),
    ]
